week_16/Python/advanced/django/endpoint/record_shop/record_store/inventory/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

week_16/Python/advanced/django/endpoint/record_shop/record_store/record_store/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('inventory/', include('inventory.urls')),
    path('admin/', admin.site.urls),
]

week_16/Python/advanced/django/endpoint/record_shop/record_store/inventory/models.py
from django.db import models

class Artist(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Album(models.Model):
    title = models.CharField(max_length=255)
    year = models.IntegerField()
    stock_level = models.IntegerField()
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

week_16/Python/advanced/django/endpoint/record_shop/record_store/inventory/views.py
from django.shortcuts import render
from django.http import HttpResponse
from inventory.models import *

def index(request):
    artists = Artist.objects.all()
    return render(request, "inventory/index.html", locals())

week_16/Python/advanced/django/endpoint/record_shop/record_store/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Record Store</title>
</head>
<body>
	{% block content %}
		
	{% endblock %}
</body>
</html>

week_16/Python/advanced/django/endpoint/record_shop/record_store/templates/inventory/index.html
{% extends "base.html" %}

{% block content %}
	{% for artist in artists %}
		<h2>{{ artist.name }}</h2>

		<ul>
			{% for album in artist.album_set.all %}
				<li>{{ album.title }} - {{ album.year }}</li>
			{% endfor %}
		</ul>
	{% endfor %}
{% endblock %}